### ISSUE TITLE
Layer for HLines, doors, and obstacles

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#131]
In Gitlab by @sainho93 on Feb 14, 2019, 09:43 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/118)]

null

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Feb 14, 2019, 09:43

assigned to @sainho93

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Feb 20, 2019, 15:38

removed milestone

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Mar 22, 2019, 13:08

removed milestone

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Jun 27, 2019, 19:50

removed milestone

**Comment by sainho93** [comment]
Finished in commit: 15302f39ec2d4cfc95273e4f5be5bb8d3787fa3f
