### ISSUE TITLE
Terminal for runing simulation

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#143]
In Gitlab by @sainho93 on Apr 9, 2019, 23:03 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/130)]

null

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Apr 9, 2019, 23:03

assigned to @sainho93

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Apr 26, 2019, 16:20

removed milestone

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on May 9, 2019, 09:36

changed due date to May 24, 2019

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on May 27, 2019, 14:01

removed due date

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Jun 17, 2019, 08:25

removed milestone

**Comment by sainho93** [comment]
Finished in commit: 20f9bcb6f355a16fa5f3c9f3cbda303df562c9d8
