### ISSUE TITLE
Selecting "Undefined" lines

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#148]
In Gitlab by @anna-braun on May 6, 2019, 16:58 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/136)]

When saving an xml-file the unused lines (walls) are saved as "Undefined", which is good. But most of the lines are saved as transitions and not as walls. When reopening the xml-file the unused lines are displayed and can be selected, but they can not be added to a room or as a door, so you have to draw them again.   

[Bahnsteig8.dxf](https://gitlab.version.fz-juelich.de/JuPedSim/jpseditor/uploads/cff5e622dbd8383994ff03cab917ba22/Bahnsteig8.dxf)    
[Bahnsteig8.xml](/uploads/ed5d896d3bf782e727aab5ace113d7f5/Bahnsteig8.xml)    

It's the same, if I draw the geometry by hand and do not use an dxf-file.

**Comment by sainho93** [comment]
Finished in commit: cffd9f4c390f672d13082caffa95e443d5659d71
