### ISSUE TITLE
Show geometry file name

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#150]
In Gitlab by @chraibi on May 13, 2019, 12:42 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/138)]

![Screenshot_2019-05-13_at_12.39.40](https://gitlab.version.fz-juelich.de/JuPedSim/jpseditor/uploads/bdd49237431e6f865480b6a5fb0719b2/Screenshot_2019-05-13_at_12.39.40.png)

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Jun 3, 2019, 10:10

removed milestone

**Comment by sainho93** [comment]
Finished in commit: 6a82a83ef2bd0e089e3df67ef51130de6c4ccf89
