### ISSUE TITLE
Widgets are too small for long names

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#151]
In Gitlab by @chraibi on May 13, 2019, 12:44 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/139)]

![Screenshot_2019-05-13_at_12.35.34](https://gitlab.version.fz-juelich.de/JuPedSim/jpseditor/uploads/624b6c8a4de0d6c7be2373158cf70d9b/Screenshot_2019-05-13_at_12.35.34.png)

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Jun 3, 2019, 10:10

removed milestone

**Comment by sainho93** [comment]
Finished in commit: 15302f39ec2d4cfc95273e4f5be5bb8d3787fa3f
This widget is no more used
