### ISSUE TITLE
Stair definition failed

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#156]
In Gitlab by @anna-braun on Jun 3, 2019, 11:09 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/144)]

JPSeditor crashes quite often, so I use to save the geometry every time when I have defined a new room. 
Then, if I define a room as stair in JPSeditor the A_x, B_y and C_z is (always) "nan" in the geometry file and I have to calculate it by hand.

**Comment by sainho93** [comment]
Finished in commit: b2bb866cc97b6ba7c7ce86fb7f0df9499531efac
