### ISSUE TITLE
New room class and wall type

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#159]
In Gitlab by @anna-braun on Jun 12, 2019, 16:24 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/147)]

For the new functions in jpscore (issue #300) there need to be some adaptations in jpseditor.    
1. wall type="track-x"
2. subroom class="Platform"
    

@sainho93 We can talk about it next week

**Comment by sainho93** [comment]
Finished in commit: 9cba82885ae82708a573494a95327ae7b1aa4a20
