### ISSUE TITLE
Background picture

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#161]
In Gitlab by @anna-braun on Jun 12, 2019, 16:28 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/148)]

For an easier drawing of geometries and if you do not have a CAD file, it should be able to load background pictures.    
    
    
@sainho93 We can talk about this next week, too.

**Comment by sainho93** [comment]
Finished in commit: da791e9d5c2185c05608af2689de5d30c5d329fe
