### ISSUE TITLE
Add default values in inifile generator

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#162]
In Gitlab by @sainho93 on Jun 25, 2019, 12:31 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/149)]

null

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Jun 25, 2019, 12:31

assigned to @sainho93

**Comment by sainho93** [comment]
Finished in commit: 0a94056eb17287aa12d9242f7b50e98826478185
