### ISSUE TITLE
Default value for all model and test

### ISSUE THREAD

**Issue by sainho93** [JuPedSim/jpseditor#178]

**Comment by sainho93** [comment]
Reference: [JuPedSim_model_parameters.xlsx](https://github.com/JuPedSim/jpseditor/files/3391531/JuPedSim_model_parameters.xlsx)

**Comment by gjaeger** [comment]
Reference for _Generalized Centrifugal Force Model_ (GCFM):

| Parameter | value |
|:----------:|:-----:|
| $$\nu$$ | 0.2| 
| $$a_{min}$$ | 0.18 m |
| $$\tau_{a}$$ | 0.43 m |
| $$b_{min}$$ | 0.20 m |
| $$b_{max}$$ | 0.25 m |
| $$\tau$$ | 0.5 s |  

Chraibi, M., Seyfried, A., & Schadschneider, A. (2014). Quantitative Validation of the Generalized Centrifugal Force Model. In Pedestrian and Evacuation Dynamics 2012 (S. 603–613). Cham: Springer International Publishing. https://doi.org/10.1007/978-3-319-02447-9_50

**Comment by sainho93** [comment]
Finished in commit: d7b518191431357e7bc6827a6b8e04b979fcd980

**Comment by gjaeger** [comment]
@sainho93 Which values have you implemented now? For which models?

**Comment by sainho93** [comment]
Finished in commit: 7ecff7383b1e5eb18239f498979032a88bf34dff

**Comment by sainho93** [comment]
@gjaeger I've implemented all tests in the xlsx.
