### ISSUE TITLE
Add debug messages in all functions

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#183]
To catch the positions in the code, where crash happens,
we need to add more debug message like 

Enter function_name
Leave function_name

**Comment by schroedtert** [comment]
Is there a possibility with C++ and Qt to get the stack trace compiler and platform independent? This would allow a more useful output than just the function names. 
Maybe something like http://boostorg.github.io/stacktrace/index.html is a way to handle this. Seems to be header only.

**Comment by chraibi** [comment]
You are right. Probably related to this [issue](https://github.com/JuPedSim/jpscore/issues/498)

**Comment by sainho93** [comment]
Finished in commit: 53eddc260e948b30e5c30d48ace6cc903be193ad
