### ISSUE TITLE
Add jpscore location to favourites 

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#197]
Add the location of `jpscore` to settings, otherwise, it's necessary to define the location for every simulation

<img width="319" alt="Screenshot 2019-10-11 12 07 14" src="https://user-images.githubusercontent.com/5772973/66643764-af422600-ec1f-11e9-86fb-b76b64990871.png">

**Comment by sainho93** [comment]
Finished in commit: 4429948b57294801219f6c22c4303922e536b607
