### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#209]
Compiling `jpseditor` under Linux failed because of a missing file `../Resources/Icons/door.png`

See screenshot 

![Screenshot 2019-12-05 16 24 01](https://user-images.githubusercontent.com/5772973/70248888-e5150e00-177b-11ea-9130-df07c41845ac.png)

**Comment by sainho93** [comment]
I knew this issue, the reason is that Qt on linux can't handle png picture like on windows or macOS. I'll fix it.

**Comment by chraibi** [comment]
@sainho93 compilation issues should be dealt with with high priority. 

```
docker run -it ubuntu
```

or

```
docker run -it centos
```

To test on linux.

**Comment by sainho93** [comment]
Finished in commit: 0eb6233e387b786c1f91b83ba5ca89b18e36ced4
