### ISSUE TITLE
Ini file creation

### ISSUE THREAD

**Issue by Squidward63** [JuPedSim/jpseditor#216]
**Bug description**
I'm getting segmentation fault whenever i try to generate the ini file. Input files used: [input_files.zip](https://github.com/JuPedSim/jpseditor/files/4443875/input_files.zip)

**Output**
<code>Enter/Return jpsDatamanager::get_crossinglist</code>
<code>Segmentation fault (core dumped)</code>

**dmesg output**
<code>[   25.479598] rfkill: input handler disabled</code>
<code>[   86.496113] show_signal_msg: 28 callbacks suppressed</code>
<code>[   86.496115] JPSeditor[1869]: segfault at 0 ip 0000557622382e85 sp 00007ffd235c9540 error 4 in JPSeditor[5576222cd000+1e9000]</code>
<code>[   86.496121] Code: 0f c1 07 48 8b 7c 24 20 44 39 f8 0f 84 d3 0a 00 00 0f 1f 40 00 49 8b 46 30 31 d2 44 89 ee 48 8b b8 08 02 00 00 e8 0b 57 f9 ff <48> 8b 08 48 89 c6 48 89 df 31 d2 ff 51 18 48 89 de 48 89 ef e8 32</code>

**Additional context**
Tested on 3 different environments: Debian 10, Ubuntu 18.04.4 LTS virtual machine, Windows 10. 
In order to compile the project i followed every step described in README.md without any issue.

**Comment by sainho93** [comment]
Hi @Squidward63 , which branch do you use to try to generate the ini file? The function `get_crossinglist` is already removed in the lastest commit on develop branch. Maybe you can try to compile with the latest commit.

**Comment by Squidward63** [comment]
That's odd, my repository is on the latest commit (0e7162a) on branch master. I'll try to recompile everything and see if it works

**Comment by Squidward63** [comment]
I was on branch master. I'll try to compile from the develop branch and see if it works. Thank you!

**Comment by Squidward63** [comment]
Yes, it works without any problem now! Thanks again.
