### ISSUE TITLE
copy geometry elements

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#39]
In Gitlab by @chraibi on Jul 10, 2015, 11:31 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/26)]

Would be nice to be able to copy "blocks" and paste them around. 

For example in case we want to duplicate the triangle in the following figure (obstacle)

![Screen_Shot_2015-07-10_at_11.30.40](https://cst.version.fz-juelich.de/jupedsim/jupedsimhttps://gitlab.version.fz-juelich.de/JuPedSim/jpseditor/uploads/5996cd4dabb0242b577bb6ef313f3773/Screen_Shot_2015-07-10_at_11.30.40.png)

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Feb 20, 2019, 15:38

removed milestone

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Feb 20, 2019, 15:38

assigned to @sainho93

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Mar 28, 2019, 19:44

removed milestone

**Comment by sainho93** [comment]
Merge issue into #67
