### ISSUE TITLE
DXF-Import not restricted to simple lines & Enhance DXF importing speed

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#55]
In Gitlab by @Erik-Andresen on Jun 18, 2017, 15:57 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/47)]

**Comment by chraibi** [comment]
In Gitlab by @sainho93 on Mar 6, 2019, 11:18

removed milestone

**Comment by anna-braun** [comment]
@sainho93 @chraibi 
Here are 3 dxf examples with different layers. 

[Archiv.zip](https://github.com/JuPedSim/jpseditor/files/3733543/Archiv.zip)

**Comment by sainho93** [comment]
Finished in commit: b84e755700ed719190da45a0b62757fee6709995
