### ISSUE TITLE
Draw lines by coordinates

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpseditor#95]
In Gitlab by @anna-braun on Nov 7, 2018, 13:31 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpseditor/issues/106)]

I tried to draw walls by typing "x" and "y", this are the results:

![1](https://gitlab.version.fz-juelich.de/JuPedSim/jpseditor/uploads/9ff5d236d9a172ef0717f865198768ff/1.png)

![2](/uploads/24db1fc87d4d8d639619c736382ecee9/2.png)

![3](/uploads/b1d4242c2d08fcfd5da7e46fedc2263f/3.png)

I think that's not what it should do.

**Comment by sainho93** [comment]
Finished in commit: 24f62728686ef09d99c2b39d6473d36db4c5449a
